#la computadora adivinara el numero que el usuario ingrese
#The computer will guess the number that the user type.

import random

def pcGuessNum(num_lim):
    while(True):
        ran_num = random.randint(1, num_lim)    #ran_num = random number is generated by pc, among 1 and the number that is in num_lim.
        print("////-////-////-////-////-////-////-////-////-////-////-////-////-////-////-////")
        print("Digite un numero entero entre 1 y",num_lim,"para que la pc adivine el numero")
        print("Type an integer number among 1 and",num_lim,"the pc will guess the number")
        print("¿Desea salir? digite el numero 0\nDo you want to exit? type the number 0")
        try:
            num_usr = int(input(": "))  #num_usr = number typed by user.
            print("////-////-////-////-////-////-////-////-////-////-////-////-////-////-////-////")
            if num_usr == 0:
                raise ZeroDivisionError
        except ValueError:
            print("Digite solo numeros\nType just numbers")
        except ZeroDivisionError:
            break
        else:
            while ran_num != num_usr:
                print("El numero tomado por la pc es",ran_num,",¿Es menor o mayor?, si es menor escriba 'm' si es mayor escriba 'M'")
                print("The number taken by pc is",ran_num,"is it lower or largest?, if is lower type 'm' if is largest type 'M'")
                men_may = input(": ")
                print("////-////-////-////-////-////-////-////-////-////-////-////-////-////-////-////")
                while not (men_may == "m" or men_may == "M"):
                        print("El numero tomado por la pc es",ran_num,",¿Es menor o mayor?, si es menor escriba 'm' si es mayor escriba 'M'")
                        print("The number taken by pc is",ran_num,"is it lower or largest?, if is lower type 'm' if is largest type 'M'")
                        men_may = input(": ")
                        print("////-////-////-////-////-////-////-////-////-////-////-////-////-////-////-////")

                if men_may == "m":
                    ran_num = random.randint(ran_num + 1, num_lim)   #If the number that the pc "took" was lower than the number typed it means that the range is among ran_num + 1(is necesary add 1 to avoid that the pc take the same number). num_lin is the limit number in this case 10.
                elif men_may == "M":
                    ran_num = random.randint(1, ran_num - 1)    #Same case but the diference is that the number type is larger than the number took by pc and is necesary subtract one.
            print("La computadora ha adivinado el numero, es:",num_usr) #If ran_num and num_usr are equal it means that the pc guessed the number.
            print("The computer has guessed the number, is",num_usr)


pcGuessNum(10)